package com.google.gwt.playground.client.mvp;

import com.google.gwt.event.logical.shared.ValueChangeEvent;
import com.google.gwt.event.logical.shared.ValueChangeHandler;
import com.google.gwt.user.client.History;

/**
 * Respond to ValueChangeEvent generated by browser History. Create and request
 * {@link Place}s as necessary.
 * 
 * @author jcarlson
 * 
 */
public abstract class TokenMapper {

    private PlaceManager placeManager;

    protected TokenMapper(PlaceManager placeManager) {
        this.placeManager = placeManager;
        History.addValueChangeHandler(new ValueChangeHandler<String>() {

            @Override
            public void onValueChange(ValueChangeEvent<String> event) {
                Place place = getPlaceForToken(event.getValue());
                if (place != null) {
                    TokenMapper.this.placeManager.request(place);
                }
            }
        });
    }

    protected abstract Place getPlaceForToken(String token);

}
